### ISSUE TITLE
Histogram Exemplars

### ISSUE THREAD

**Issue by janstenpickle** [permutive-engineering/prometheus4cats#14]
Should we support [histogram exemplars](https://vbehar.medium.com/using-prometheus-exemplars-to-jump-from-metrics-to-traces-in-grafana-249e721d4192) in this release? 

My gut says no, as they aren't commonly used. This would mean if do want to support them in the future we would likely have to target them at `2.x`.

WDYT @TimWSpence @bastewart?

**Comment by alejandrohdezma** [comment]
Support added in #65
